### PR TITLE
basic sound support

### PR DESCRIPTION
**Pull request by jice-nospam**
This is a first draft for feedback. I didn't implement stop_sound and unload_sound yet.
And for now it's only working on native side because I haven't found an easy way to integrate the wavefile loader with unrust asset database system. We'll probably have to fork wavefile for that.

The main API is SoundSystem. It's available at world.sound. It provides the user methods (load_sound, play_sound). Check the new sound example for a usage example.

The Generator is the sound dedicated thread. SoundSystem communicate with it through SoundEvents.
It contains the samples cache and CHANNEL_COUNT (4) stereo channels.

The channels can play a mono or stereo buffer, do panning and dynamic resampling if the buffer sample rate it not equal to the driver sample rate. It's better and faster to use samples that use the same rate as the driver.

This is a basic system, as planed for 0.1.1. Not sure you want to keep it further. It would be better to find a robust sound library but until then, it can do the job.

### CODE REVIEW

**Comment by jice-nospam** [comment]
This is the WaveFile loader to be integrated to the asset database : 
https://github.com/ledbettj/wavefile/blob/master/src/lib.rs#L94

**Comment by edwin0cheng** [comment]
I just changed to use hound crate, which is pure rust based so it is possible to compile in wasm32-unknown-unknown target. (I tested it)

**Comment by edwin0cheng** [comment]
And im integrating unrust asset system to the sound system now. But it is a little bit tricky, because all resource in Web need to use futures to handle (As it is loaded asynchronously).

All other resources right now are loaded as lazily, which means if the resources are not ready, it will skip it. Maybe i have to wrap the SoundHandle struct to allow this kind of mechanism.

**Comment by edwin0cheng** [comment]
Ok, after https://github.com/edwin0cheng/unrust/pull/36/commits/e426bbf31486f03923353b852ae10a07d66992ed , it works in both native and web now.

When the sound handle is called with play_sound but it is not ready (Still loading), it will be added to `pending_play` queue for later playing. 

see https://github.com/edwin0cheng/unrust/pull/36/commits/e426bbf31486f03923353b852ae10a07d66992ed#diff-050d12545b1bbfa5ddedf8e07c8d8017R99

**Comment by edwin0cheng** [comment]
Anything i missed in here ? If no, i am okay to merge it :)

**Comment by jice-nospam** [comment]
It looks great!

**Comment by edwin0cheng** [comment]
Because normally we do not have a lot of sound handle, and rust HashMap is slow for few keys (It hash function is optimalize for security, not optimalize for speed), so BTreeSet would be faster.

And in fact, i already added fnv crate for faster hashmap, but i forget about that, haha

**Pull request merged**
