### PR TITLE
Some features for webgl/uni-app

### PR DESCRIPTION
**Pull request by jice-nospam**
- possibility to hide mouse cursor with uni-app::AppConfig.show_cursor=false

- uni-app::AppEvent::MousePos event

- added webgl::uniform_1fv

They work fine on native. Can't test the web part right now as wasm target is broken on nightly

### CODE REVIEW

**Comment by edwin0cheng** [comment]
You could use a older rust-nighty version to test right now : 
`rustup override set nightly-2019-03-01`

**Comment by jice-nospam** [comment]
ah thanks, I was looking for a way to rollback to a previous nightly
version. I'm checking that asap

2018-03-11 23:46 GMT+01:00 Edwin Cheng <notifications@github.com>:

**Comment by jice-nospam** [comment]
Ok the mouse cursor/pos works fine with webgl.
I couldn't test the `uniform_1fv` function though, as the shader that is using it in my project is not yet compatible with webgl.
I also added an App::get_params to have a standard way to get command line params.
Example :

- native

`cargo run param=value param2=value2 param3`
=> App::get_params() == vec!["param=value","param2=value2","param3"]

- web

`http://localhost:8000/?param=value&param2=value2&param3`
=> App::get_params() == vec!["param=value","param2=value2","param3"]

**Comment by edwin0cheng** [comment]
I wanna know should i change the uniform_1fv interface without the count argument ?

**Pull request merged**
